version: '3.7'

networks:
  mynetwork:
    external: true

services:
  zookeeper:
    image: strimzi/kafka:0.17.0-kafka-2.4.0
    container_name: "zookeeper"
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - mynetwork

  kafka:
    image: strimzi/kafka:0.17.0-kafka-2.4.0
    container_name: "kafka"
    hostname: "kafka"
    networks:
      - mynetwork
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties \
      --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} \
      --override advertised.host.name=$${KAFKA_ADVERTISED_HOST_NAME} \
      --override advertised.port=$${KAFKA_ADVERTISED_PORT} \
      --override offsets.topic.replication.factor=$${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      # Following line is needed for Kafka versions 0.11+
      # in case you run less than 3 Kafka brokers in your
      # cluster because the broker config
      # `offsets.topic.replication.factor` (default: 3)
      # is now enforced upon topic creation
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1